"""
rewiring_interpolation.py — Referee 1 major comment 4

Interpolates continuously between the correlated multiplex (G_vig=G_game)
and the uncorrelated multiplex (independent realizations) via degree-
preserving edge rewiring, to test whether the transition in cooperation is
continuous or discontinuous with respect to inter-layer edge correlation --
following the procedure of Battiston, Perc & Latora (2017, New J. Phys. 19,
073017, their Fig. 2 parametrized by omega), whose mechanism traces back to
Diakonova, Nicosia, Latora & San Miguel (2016, New J. Phys. 18, 023010).

Rewiring mechanism: start with G_vig = G_game (r=0, edge overlap omega=1).
To reach a target r, perform degree-preserving double-edge-swaps within
G_vig, restricted to pairs of edges that still overlap with G_game (so each
successful swap directly reduces the overlap), until a fraction r of the
*original* overlapping edges have been swapped away. This keeps G_vig's own
degree sequence exactly fixed and the edge count fixed throughout -- only
which edges overlap with G_game changes. r=1 attempts to remove as much
overlap as double-edge-swaps allow, approximating (but not exactly
equalling) an independent realization; the actual resulting edge overlap
omega is measured directly from the rewired network at every r, rather
than assumed from the closed-form omega=(1-r)/(1+r) derived in the cited
references for regular random graphs, since Barabasi-Albert (not used
here, see below) is degree-heterogeneous and even Erdos-Renyi's omega(r)
need not follow that closed form exactly at finite N.

Scope (agreed with Maria 2026-09-03): Sec. III.C confirms ER z=4 is the
topology with by far the largest correlated-vs-uncorrelated sensitivity
(mean |rho difference| up to 0.22, an order of magnitude above BA). The
referee's own comment points at Fig. 5 (originally "Figure 4" before the
Fig. 1 flowchart insertion shifted numbering), which shows theta=0.2, 0.3,
0.5; of these, theta=0.2 shows the clearest correlated/uncorrelated
divergence (theta=0.5 shows essentially none). Rather than a single
(b, theta) point, this sweeps b across the region where the two collapse
boundaries diverge (the correlated boundary reaches b>2.0 by L=4 while the
uncorrelated one stays near b~1.3-1.5), to see whether the r-transition's
shape itself depends on b, not just its endpoints -- producing a
rho(r, b) map at fixed theta=0.2, analogous to the rho(b, theta) heatmaps
used throughout the paper.

Grid: b in {1.3, 1.5, 1.7, 1.9, 2.0}, r in {0.0, 0.1, ..., 1.0} (11
values), L in {2, 4}, ER z=4, theta=0.2 fixed. 100 replications per point,
matching the main text. G_game is a single fixed network realization
(consistent with the rest of the paper's convention of one realization per
topology; realization-to-realization robustness is the separate R1#3/R2#7
study).

NOTE (2026-09-03): written but not yet run -- scheduled after comments 7
and 8's studies (and the R2#6 follow-up) free up compute. Estimated
~15-30 min based on a timing smoke test (ER z=4, theta=0.2, b=1.7: 3.5s/
point at L=2, 10.5s/point at L=4, both far from any r-transition; points
near the transition are expected to be slower, as seen elsewhere in this
robustness campaign).
"""
import os, sys, time
import numpy as np
import networkx as nx
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
from model import build_network, game_csr, shells_csr, geometric_kernel, run_replications

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
os.makedirs(OUT_DIR, exist_ok=True)
OUT_CSV = os.path.join(OUT_DIR, "rewiring_interpolation.csv")

TOPO, Z = "ER", 4
THETA = 0.2
B_VALUES = [1.3, 1.5, 1.7, 1.9, 2.0]
R_VALUES = [round(0.1 * i, 1) for i in range(11)]  # 0.0, 0.1, ..., 1.0
L_VALUES = [2, 4]
N_REP = 100
LAM = 0.5
N_NODES = 1000
K_FERMI = 0.1


def _edge_key(u, v):
    return (u, v) if u < v else (v, u)


def build_rewired_vig(G_game, r, seed, max_tries_factor=50):
    """Degree-preserving double-edge-swaps within a copy of G_game,
    restricted to edges still overlapping with G_game, until the *measured*
    remaining overlap has dropped to a target of (1-r) times the original
    overlap (= all of G_game's edges, since G_vig starts identical to
    G_game). Targeting the overlap count directly, rather than a fixed
    number of swap attempts, matters because each successful swap removes
    two overlapping edges at once (occasionally reintroducing one by
    chance), so swap count and overlap reduction are not proportional.
    r=0 returns an exact copy of G_game (omega=1); r=1 pushes the measured
    overlap down as far as double-edge-swaps allow within the try budget
    (it does not reach exactly 0, since some overlap is regenerated by
    chance as edges are randomly reassigned)."""
    rng = np.random.default_rng(seed)
    Gv = G_game.copy()
    game_edges = set(_edge_key(u, v) for u, v in G_game.edges())
    n0 = len(game_edges)
    target_overlap = int(round((1 - r) * n0))
    if target_overlap >= n0:
        return Gv

    overlap = [e for e in game_edges if Gv.has_edge(*e)]
    tries = 0
    max_tries = max_tries_factor * n0
    while len(overlap) > target_overlap and tries < max_tries and len(overlap) >= 2:
        tries += 1
        i, j = rng.choice(len(overlap), size=2, replace=False)
        a, b = overlap[i]
        c, d = overlap[j]
        if len({a, b, c, d}) < 4:
            continue
        if rng.random() < 0.5:
            new1, new2 = _edge_key(a, d), _edge_key(c, b)
        else:
            new1, new2 = _edge_key(a, c), _edge_key(b, d)
        if new1 == new2 or Gv.has_edge(*new1) or Gv.has_edge(*new2):
            continue
        Gv.remove_edge(a, b)
        Gv.remove_edge(c, d)
        Gv.add_edge(*new1)
        Gv.add_edge(*new2)
        overlap[i], overlap[j] = None, None
        overlap = [e for e in overlap if e is not None]
        if new1 in game_edges:
            overlap.append(new1)
        if new2 in game_edges:
            overlap.append(new2)
    return Gv


def measured_omega(Gv, G_game):
    """Actual edge overlap fraction, measured directly (not the closed-form
    estimate), as described in our R1#4 response."""
    game_edges = set(_edge_key(u, v) for u, v in G_game.edges())
    vig_edges = set(_edge_key(u, v) for u, v in Gv.edges())
    return len(game_edges & vig_edges) / len(game_edges)


def main():
    rows = []
    if os.path.exists(OUT_CSV):
        rows = pd.read_csv(OUT_CSV).to_dict("records")
        print(f"Resuming: {len(rows)} results already present in {OUT_CSV}")
    done = {(r["b"], r["r"], r["L"]) for r in rows}

    t0 = time.time()
    G_game = build_network(TOPO, N_NODES, Z, seed=7)
    gp, gd = game_csr(G_game)

    for b in B_VALUES:
        for r in R_VALUES:
            Gv = build_rewired_vig(G_game, r, seed=hash((b, r)) % (2**31))
            omega = measured_omega(Gv, G_game)
            sp_by_L = {}
            for L in L_VALUES:
                key = (b, r, L)
                if key in done:
                    continue
                if L not in sp_by_L:
                    sp_by_L[L] = shells_csr(Gv, L)
                sp, sd = sp_by_L[L]
                al = geometric_kernel(L, LAM)
                t1 = time.time()
                rhos = run_replications(gp, gd, sp, sd, al, b, THETA, K=K_FERMI,
                                         n_rep=N_REP, n_jobs=-1, base_seed=hash((b, r, L)) % (2**31))
                dt = time.time() - t1
                rows.append(dict(topo=f"{TOPO}_z{Z}", theta=THETA, b=b, r=r, L=L,
                                  omega=omega, rho_mean=float(rhos.mean()),
                                  rho_std=float(rhos.std(ddof=1)), seconds=dt))
                print(f"b={b} r={r} L={L} omega={omega:.3f}: "
                      f"rho={rhos.mean():.4f} ({dt:.1f}s)", flush=True)
                pd.DataFrame(rows).to_csv(OUT_CSV, index=False)

    print(f"TOTAL TIME: {time.time()-t0:.1f}s")
    print("Saved:", OUT_CSV)


if __name__ == "__main__":
    main()
